#!/usr/bin/env bash
set -Eeuo pipefail

choice="$(
    printf 'lock\nlogout\nreboot\npoweroff\n' |
        rofi -dmenu -p power
)"

case "$choice" in
    lock)
        i3lock -c 000000
        ;;
    logout)
        i3-msg exit
        ;;
    reboot)
        systemctl reboot
        ;;
    poweroff)
        systemctl poweroff
        ;;
esac
